print("=+=+=+=+=+ Data Diri Mahasiswa =+=+=+=+=+=")
nim = input("NIM:")
nama = input("Nama Lengkap: ")
jurusan = input("Jurusan: ")
alamat = input("Alamat: ")

print("==========================================")
print('HASIL CETAK DATA YANG DI ATAS')
print("NIM      : " +str(nim)+"|")
print("Nama     : " +str(nama)+"|")
print("Jurusan  : " +str(jurusan)+"|")
print("Alamat   : " +str(alamat)+"|")
print("===========================================")

print("+=+=+=+=+=+=++=+=+=+=+=+=++=+=+=+=+=+=++=+=")